// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Asset: head_utility_mp
// Convert Time: 08/29/2021 16:45:42

main()
{
	level.cac_attributes[ "mobility" ][ "head_utility_mp" ] = 0;
	level.cac_attributes[ "armor_bullet" ][ "head_utility_mp" ] = 0;
	level.cac_attributes[ "armor_explosive" ][ "head_utility_mp" ] = 0;

	level.cac_assets[ "usa_sog" ][ "head_utility_mp" ] = "c_usa_sog_mp_head_5";
	level.cac_assets[ "vtn_nva" ][ "head_utility_mp" ] = "c_vtn_nva_mp_head_5";
	level.cac_assets[ "usa_cia" ][ "head_utility_mp" ] = "c_usa_cia_mp_head_5";
	level.cac_assets[ "usa_ciawin" ][ "head_utility_mp" ] = "c_usa_ciawin_mp_head_5";
	level.cac_assets[ "rus_spet" ][ "head_utility_mp" ] = "c_rus_spet_mp_head_5";
	level.cac_assets[ "rus_spetwin" ][ "head_utility_mp" ] = "c_rus_spetwin_mp_head_5";
	level.cac_assets[ "cub_rebels" ][ "head_utility_mp" ] = "c_cub_rebels_mp_head_5";
	level.cac_assets[ "cub_tropas" ][ "head_utility_mp" ] = "c_cub_tropas_mp_head_5";


	level.cac_functions[ "precache" ][ "head_utility_mp" ] = ::precache;
	level.cac_functions[ "set_head_model" ][ "head_utility_mp" ] = ::set_head_model;
	level.cac_functions[ "set_specialties" ][ "head_utility_mp" ] = ::set_specialties;
}

precache( faction )
{
	model = level.cac_assets[ faction ][ "head_utility_mp" ];
	PrecacheModel( model );

}

set_head_model( faction )
{
	model = level.cac_assets[ faction ][ "head_utility_mp" ];
	self Attach( model, "", true );
}

set_specialties()
{
}