// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Asset: hardened_mp
// Convert Time: 08/29/2021 16:45:42

main()
{
	level.cac_attributes[ "mobility" ][ "hardened_mp" ] = 0;
	level.cac_attributes[ "armor_bullet" ][ "hardened_mp" ] = 0;
	level.cac_attributes[ "armor_explosive" ][ "hardened_mp" ] = 0;
	level.cac_attributes[ "sprint_time_total" ][ "hardened_mp" ] = 4;
	level.cac_attributes[ "sprint_time_cooldown" ][ "hardened_mp" ] = 0;

	level.cac_assets[ "usa_sog" ][ "hardened_mp" ] = "c_usa_sog_mp_body_flak";
	level.cac_assets[ "vtn_nva" ][ "hardened_mp" ] = "c_vtn_nva_mp_body_flak";
	level.cac_assets[ "usa_cia" ][ "hardened_mp" ] = "c_usa_cia_mp_body_flak";
	level.cac_assets[ "usa_ciawin" ][ "hardened_mp" ] = "c_usa_ciawin_mp_body_flak";
	level.cac_assets[ "rus_spet" ][ "hardened_mp" ] = "c_rus_spet_mp_body_flak";
	level.cac_assets[ "rus_spetwin" ][ "hardened_mp" ] = "c_rus_spetwin_mp_body_flak";
	level.cac_assets[ "cub_rebels" ][ "hardened_mp" ] = "c_cub_rebels_mp_body_flak";
	level.cac_assets[ "cub_tropas" ][ "hardened_mp" ] = "c_cub_tropas_mp_body_flak";

	level.cac_assets[ "usa_sog" ][ "viewmodel" ][ "hardened_mp" ] = "viewmodel_usa_sog_flak_arms";
	level.cac_assets[ "vtn_nva" ][ "viewmodel" ][ "hardened_mp" ] = "viewmodel_vtn_nva_flak_arms";
	level.cac_assets[ "usa_cia" ][ "viewmodel" ][ "hardened_mp" ] = "viewmodel_usa_cia_flak_arms";
	level.cac_assets[ "usa_ciawin" ][ "viewmodel" ][ "hardened_mp" ] = "viewmodel_usa_ciawin_flak_arms";
	level.cac_assets[ "rus_spet" ][ "viewmodel" ][ "hardened_mp" ] = "viewmodel_rus_spet_flak_arms";
	level.cac_assets[ "rus_spetwin" ][ "viewmodel" ][ "hardened_mp" ] = "viewmodel_rus_spetwin_flak_arms";
	level.cac_assets[ "cub_rebels" ][ "viewmodel" ][ "hardened_mp" ] = "viewmodel_cub_rebels_flak_arms";
	level.cac_assets[ "cub_tropas" ][ "viewmodel" ][ "hardened_mp" ] = "viewmodel_cub_tropas_flak_arms";

	level.cac_functions[ "precache" ][ "hardened_mp" ] = ::precache;
	level.cac_functions[ "set_body_model" ][ "hardened_mp" ] = ::set_body_model;
	level.cac_functions[ "set_specialties" ][ "hardened_mp" ] = ::set_specialties;
	level.cac_functions[ "get_default_head" ][ "hardened_mp" ] = ::get_default_head;
}

precache( faction )
{
	model = level.cac_assets[ faction ][ "hardened_mp" ];
	PrecacheModel( model );

	viewmodel = level.cac_assets[ faction ][ "viewmodel" ][ "hardened_mp" ];
	PrecacheModel( viewmodel );
}

set_body_model( faction )
{
	model = level.cac_assets[ faction ][ "hardened_mp" ];
	self SetModel( model );

	viewmodel = level.cac_assets[ faction ][ "viewmodel" ][ "hardened_mp" ];
	self SetViewModel( viewmodel );
}

set_specialties()
{
}

get_default_head()
{
	return( "head_flak_mp" );
}