// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
// Asset: standard_mp
// Convert Time: 08/29/2021 16:45:42

main()
{
	level.cac_attributes[ "mobility" ][ "standard_mp" ] = 0;
	level.cac_attributes[ "armor_bullet" ][ "standard_mp" ] = 0;
	level.cac_attributes[ "armor_explosive" ][ "standard_mp" ] = 0;
	level.cac_attributes[ "sprint_time_total" ][ "standard_mp" ] = 4;
	level.cac_attributes[ "sprint_time_cooldown" ][ "standard_mp" ] = 0;

	level.cac_assets[ "usa_sog" ][ "standard_mp" ] = "c_usa_sog_mp_body_standard";
	level.cac_assets[ "vtn_nva" ][ "standard_mp" ] = "c_vtn_nva_mp_body_standard";
	level.cac_assets[ "usa_cia" ][ "standard_mp" ] = "t5_gfl_type97_body_mp";
	level.cac_assets[ "usa_ciawin" ][ "standard_mp" ] = "t5_gfl_type97_body_mp";
	level.cac_assets[ "rus_spet" ][ "standard_mp" ] = "t5_gfl_ak12_body_mp";
	level.cac_assets[ "rus_spetwin" ][ "standard_mp" ] = "t5_gfl_ak12_body_mp";
	level.cac_assets[ "cub_rebels" ][ "standard_mp" ] = "c_cub_rebels_mp_body_standard";
	level.cac_assets[ "cub_tropas" ][ "standard_mp" ] = "c_cub_tropas_mp_body_standard";

	level.cac_assets[ "usa_sog" ][ "viewmodel" ][ "standard_mp" ] = "viewmodel_usa_sog_standard_arms";
	level.cac_assets[ "vtn_nva" ][ "viewmodel" ][ "standard_mp" ] = "viewmodel_vtn_nva_standard_arms";
	level.cac_assets[ "usa_cia" ][ "viewmodel" ][ "standard_mp" ] = "viewmodel_usa_cia_standard_arms";
	level.cac_assets[ "usa_ciawin" ][ "viewmodel" ][ "standard_mp" ] = "viewmodel_usa_ciawin_standard_arms";
	level.cac_assets[ "rus_spet" ][ "viewmodel" ][ "standard_mp" ] = "viewmodel_rus_spet_standard_arms";
	level.cac_assets[ "rus_spetwin" ][ "viewmodel" ][ "standard_mp" ] = "viewmodel_rus_spetwin_standard_arms";
	level.cac_assets[ "cub_rebels" ][ "viewmodel" ][ "standard_mp" ] = "viewmodel_cub_rebels_standard_arms";
	level.cac_assets[ "cub_tropas" ][ "viewmodel" ][ "standard_mp" ] = "viewmodel_cub_tropas_standard_arms";

	level.cac_functions[ "precache" ][ "standard_mp" ] = ::precache;
	level.cac_functions[ "set_body_model" ][ "standard_mp" ] = ::set_body_model;
	level.cac_functions[ "set_specialties" ][ "standard_mp" ] = ::set_specialties;
	level.cac_functions[ "get_default_head" ][ "standard_mp" ] = ::get_default_head;
}

precache( faction )
{
	model = level.cac_assets[ faction ][ "standard_mp" ];
	PrecacheModel( model );

	viewmodel = level.cac_assets[ faction ][ "viewmodel" ][ "standard_mp" ];
	PrecacheModel( viewmodel );
}

set_body_model( faction )
{
	model = level.cac_assets[ faction ][ "standard_mp" ];
	self SetModel( model );

	viewmodel = level.cac_assets[ faction ][ "viewmodel" ][ "standard_mp" ];
	self SetViewModel( viewmodel );
}

set_specialties()
{
}

get_default_head()
{
	return( "head_standard_mp" );
}