// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	character\gfl\character_gfl_hk416_v2_mp::main();
	self.voice = "german";
}

precache()
{
	character\gfl\character_gfl_hk416_v2_mp::precache();
}
