// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	character\gfl\character_gfl_type89_mp::main();
	self.voice = "vietnamese";
}

precache()
{
	character\gfl\character_gfl_type89_mp::precache();
}
