// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	character\gfl\character_gfl_m1903_sitting::main();
	self.voice = "american";
}

precache()
{
	character\gfl\character_gfl_m1903_sitting::precache();
}
