// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("t5_gfl_m1903_body_sitting");
	self.headModel = "t5_gfl_m1903_head";
	self attach(self.headModel, "", true);
	self attach("t5_gfl_m1903_hair", "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("t5_gfl_m1903_body_sitting");
	precacheModel("t5_gfl_m1903_head");
	precacheModel("t5_gfl_m1903_hair");
}
