// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("t5_gfl_nyto_body");
	self.headModel = "t5_gfl_nyto_head";
	self attach(self.headModel, "", true);
	self attach("t5_gfl_nyto_hair", "", true);
	self attach("t5_gfl_nyto_leg", "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("t5_gfl_nyto_body");
	precacheModel("t5_gfl_nyto_head");
	precacheModel("t5_gfl_nyto_hair");
	precacheModel("t5_gfl_nyto_leg");
}
