// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("t5_gfl_type97_body");
	self.headModel = "t5_gfl_type97_head";
	self attach(self.headModel, "", true);
	self attach("t5_gfl_type97_hair", "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("t5_gfl_type97_body");
	precacheModel("t5_gfl_type97_head");
	precacheModel("t5_gfl_type97_hair");
}
