// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("t5_gfl_m16a1_body");
	self.headModel = "t5_gfl_m16a1_head";
	self attach(self.headModel, "", true);
	self.voice = "american";
	self.skeleton = "base";
}

precache()
{
	precacheModel("t5_gfl_m16a1_body");
	precacheModel("t5_gfl_m16a1_head");
}
